name: robbmann
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
  - conda-forge
dependencies:
  # Base interpreter(s)
  - python>=3.7

  # Command-line utilities
  - aspell
  - condax
  - cookiecutter
  - fzf
  - jq
  - make
  - pipx
  - yq

  # Base Jupyter
  - jupyterlab
