" Author: Robert A. Enzmann
" License: Do anything you like.
"
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"   !       This vim configuration is portable       !
"   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
"
" Thanks to: https://stackoverflow.com/a/3384476/13215205
"
" $ git clone --recursive git@github.com:renzmann/renzmann
" $ vim -u renzmann/.vim/vimrc
"
" Runtime path setup {{{
let &runtimepath = printf('%s/vimfiles,%s,%s/vimfiles/after', $VIM, $VIMRUNTIME, $VIM)
let $MYVIMHOME = expand('<sfile>:p:h')
let &runtimepath = printf('%s,%s,%s/after', $MYVIMHOME, &runtimepath, $MYVIMHOME)
if has('nvim')
  let &runtimepath = printf('%s,%s,%s/after', stdpath('config'), &runtimepath, stdpath('config').'/after')
endif
let &packpath = &runtimepath

" If the current project defines a project-level .vimrc, source it here
if filereadable("project.vim") && !exists("g:loaded_renzmann_project")
  source project.vim
  let g:loaded_renzmann_project = 1
endif
" }}}

" Editor Settings: {{{
" Make sure that `stty start undef` and `stty -ixon` are in ~/.bashrc
" https://stackoverflow.com/a/21808952
set nocompatible
set background=dark
set encoding=utf-8
set cursorline
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=
set hidden
set linebreak
set shiftround
set number
set relativenumber
set nowrap
set hlsearch
set wildignore=*.o,*.obj,*.db-whl,*.db-shm,*node_modules*,*.venv*,tags,.*.un~,*.pyc
set list listchars=tab:>\ ,trail:·
set mouse=a
set showcmd
set foldmethod=marker
set foldmarker={{{,}}}
set completeopt=menu,menuone,preview
" At one point I had set this to the below. See the following for why that might
" not be a great idea:
" https://gist.github.com/romainl/7e2b425a1706cd85f04a0bd8b3898805
" set path=.,,./**,**,

" Sometimes prevents crazy bad highlighted lines when they shouldn't be
set t_ut=

if has('win32')
  set termguicolors
endif

" Set grep program to the much faster ripgrep
if executable('rg')
  set grepprg=rg\ --vimgrep
endif

" Auto set Omnifunc completion to `syntaxcomplete`
if has("autocmd") && exists("+omnifunc")
endif

augroup default
  autocmd!
  " Automatically open the quickfix menu if there are results sent to it
  autocmd QuickFixCmdPost [^l]* cwindow
  " Common save hooks
  autocmd BufWritePre *
    \ " Automatically create folders
    \ if '<afile>' !~ '^scp:' && !isdirectory(expand('<afile>:h')) |
      \ call mkdir(expand('<afile>:h'), 'p') |
    \ endif
  autocmd Filetype *
    \ if &omnifunc == "" |
      \ setlocal omnifunc=syntaxcomplete#Complete |
    \ endif
augroup END

if has('win32')
  set nocursorline
  set t_vb=
  if has('gui')
    set guifont=DejaVu_Sans_Mono_for_Powerline:h11
    set guioptions-=T
    set t_vb=
  end
end
" }}}

" Color theme {{{
augroup desert_override
  autocmd!
  " Italic comments
  autocmd ColorScheme desert hi Comment cterm=italic gui=italic ctermfg=73
  " Quieter line numbers
  autocmd ColorScheme desert hi CursorLineNr ctermbg=236 ctermfg=73 cterm=NONE guibg=#303030 guifg=#5fafaf gui=NONE
  autocmd ColorScheme desert hi CursorLine ctermbg=236 ctermfg=NONE cterm=NONE guibg=#303030 guifg=NONE gui=NONE
  autocmd ColorScheme desert hi LineNr ctermbg=236 ctermfg=242 cterm=NONE guibg=grey15 guifg=#6c6c6c gui=NONE
  " Quieter fold text
  autocmd ColorScheme desert hi Folded ctermfg=246 cterm=NONE guibg=grey15 guifg=#6c6c6c gui=NONE
augroup END

" Default colos that are okay:
" colo torte
" colo murphy
" colo koehler
" colo desert
" colo evening

" Custom colors that are okay:
" colo apprentice  " github.com/romainl/Apprentice
" colo gruvbox     " github.com/morhetz/gruvbox
" colo iceberg     " github.com/cocopon/iceberg.vim
colo nord        " github.com/arcticicestudio/nord-vim

" }}}

" Common abbreviations {{{
cabbrev fidn find
cabbrev greo grep
cabbrev vsf vert sfind
cabbrev %% %:p:h
" `cd current file`
cabbrev ccf cd %:p:h
" }}}

" netrw customization: {{{
" tree style list
let g:netrw_liststyle = 3
" suppress the banner
let g:netrw_banner = 0
" }}}

" slime customization: {{{
let g:slime_target = "tmux"
" I always have the REPL on the right, vertical split.
let g:slime_default_config = {"socket_name": "default", "target_pane": "1"}
" }}}
