(global-set-key (kbd "C-c t w") 'delete-trailing-whitespace)
(global-set-key (kbd "C-c f") 'find-file-at-point)
(global-set-key (kbd "C-c p a") 'pyvenv-activate)
(global-set-key (kbd "C-c p d") 'pyvenv-deactivate)
(global-set-key (kbd "C-c p f") 'elpy-black-fix-code)
(global-set-key (kbd "C-c s i") (lambda () (interactive) (find-file "~/.emacs.d/init.el")))
(global-set-key (kbd "C-c s k") (lambda () (interactive) (find-file "~/.emacs.d/keybindings.el")))
(global-set-key (kbd "C-c v") 'evil-mode)
(global-set-key (kbd "C-c f") 'recentf-open-files)
(global-set-key (kbd "C-c c") 'comment-or-uncomment-region)
